services:
  db:
    image: postgres:15.8
    environment:
      POSTGRES_DB: store
      POSTGRES_USER: pearlThoughts
      POSTGRES_PASSWORD: pt034
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: